var AppConstants = {
  UPDATE_CHAR_NAME: "UPDATE_CHAR_NAME",
  UPDATE_CHAR_RACE: "UPDATE_CHAR_RACE",
  UPDATE_CHAR_LEVEL: "UPDATE_CHAR_LEVEL",
  UPDATE_BASE_HP: "UPDATE_BASE_HP"
}

export default AppConstants;