var AppConstants = {
  UPDATE_CHAR_NAME: "UPDATE_CHAR_NAME",
  UPDATE_CHAR_RACE: "UPDATE_CHAR_RACE",
  UPDATE_CHAR_LEVEL: "UPDATE_CHAR_LEVEL",
  UPDATE_BASE_HP: "UPDATE_BASE_HP",
  UPDATE_STRENGTH: "UPDATE_STRENGTH",
  UPDATE_DEXTERITY: "UPDATE_DEXTERITY",
  UPDATE_CONSTITUTION: "UPDATE_CONSTITUTION",
  UPDATE_INTELLIGENCE: "UPDATE_INTELLIGENCE",
  UPDATE_WISDOM: "UPDATE_WISDOM",
  UPDATE_CHARISMA: "UPDATE_CHARISMA"
}

export default AppConstants;